install:
  - ps: cinst pester -y

build_script:
  - ps: Copy-Item "C:\projects\powershell-module\Rubrik" "C:\Program Files\WindowsPowerShell\Modules"

test_script:
  - ps: . .\Tests\Connect-Rubrik.Tests.ps1 -Test